
version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  error-server:
    image: "fusakla/error-server:0.0.2"
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    dns: 8.8.8.8
    ports:
      - 9090:9090
    restart: always


  grafana:
    image: grafana/grafana:5.2.0-beta1
    ports:
      - 3000:3000
    dns: 8.8.8.8
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/grafana.env
    restart: always


  alertmanager:
    image: prom/alertmanager:v0.14.0
    ports:
      - 9093:9093
    dns: 8.8.8.8
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
