global:
  scrape_interval:     5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'error-server'
    metrics_path: "/demo/metrics"
    scheme: http
    static_configs:
         - targets: ['error-server:8080']

rule_files:
  - '/etc/prometheus/rules/*.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
