global:
  scrape_interval:     5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'fusakla-cz'
    static_configs:
         - targets: ['fusakla.cz/demo/metrics']

rule_files:
  - '/etc/prometheus/rules/*.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
