apiVersion: 1

datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
