{
 "title": "Prometheus demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request count by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[30s])) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count[30s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request  duration histohram  by endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[30s])) by (endpoint, le))",
     "legendFormat": "0.5 quantile for {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.7, sum(rate(http_request_duration_seconds_bucket[30s])) by (endpoint, le))",
     "legendFormat": "0.7 quantile for {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[30s])) by (endpoint, le))",
     "legendFormat": "0.9 quantile for {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[30s])) by (endpoint, le))",
     "legendFormat": "0.99 quantile for {{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"error-server.*\"}[30s])"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"error-server.*\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "UPtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"error-server.*\"} "
    }
   ]
  },
  {
   "title": "# of instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{instance=~\"error-server.*\"})"
    }
   ]
  }
 ]
}