groups:
- name: demo-alert
  rules:
  - alert: HighRequestCount
    expr: sum(increase(http_request_duration_seconds_count{endpoint="/demo",instance=~"fusakla.*"}[30s])) by (instance) > 100
    labels:
      severity: prometheus-demo
    annotations:
      title: "There is more than 100 requests per 30s on fusakla.cz/demo"
